import type { LocalizedString } from '../i18n';

export interface NavItem {
  id: string;
  title: LocalizedString;
  icon?: string;
}

export interface NavGroup {
  title: LocalizedString;
  items: NavItem[];
}

export const navigation: NavGroup[] = [
  {
    title: {
      en: 'OVERVIEW',
      zh: '概览',
      ko: '개요',
      ja: '概要',
      ru: 'ОБЗОР',
      es: 'RESUMEN',
      pt: 'VISÃO GERAL',
      it: 'PANORAMICA',
      vi: 'TỔNG QUAN',
    },
    items: [
      {
        id: 'getting-started',
        title: {
          en: 'Getting Started',
          zh: '快速开始',
          ko: '시작하기',
          ja: 'はじめに',
          ru: 'Начало работы',
          es: 'Primeros pasos',
          pt: 'Primeiros passos',
          it: 'Per iniziare',
          vi: 'Bắt đầu',
        },
        icon: 'rocket',
      },
      {
        id: 'faq',
        title: {
          en: 'FAQ',
          zh: '常见问题',
          ko: 'FAQ',
          ja: 'よくある質問',
          ru: 'FAQ',
          es: 'Preguntas frecuentes',
          pt: 'Perguntas frequentes',
          it: 'Domande frequenti',
          vi: 'Câu hỏi thường gặp',
        },
        icon: 'help-circle',
      },
    ],
  },
  {
    title: {
      en: 'AUTHENTICATION',
      zh: '认证',
      ko: '인증',
      ja: '認証',
      ru: 'АУТЕНТИФИКАЦИЯ',
      es: 'AUTENTICACIÓN',
      pt: 'AUTENTICAÇÃO',
      it: 'AUTENTICAZIONE',
      vi: 'XÁC THỰC',
    },
    items: [
      {
        id: 'authentication',
        title: {
          en: 'Authentication',
          zh: '身份认证',
          ko: '인증',
          ja: '認証',
          ru: 'Аутентификация',
          es: 'Autenticación',
          pt: 'Autenticação',
          it: 'Autenticazione',
          vi: 'Xác thực',
        },
        icon: 'key',
      },
    ],
  },
  {
    title: {
      en: 'API REFERENCE',
      zh: 'API 参考',
      ko: 'API 레퍼런스',
      ja: 'API リファレンス',
      ru: 'СПРАВОЧНИК API',
      es: 'REFERENCIA DE API',
      pt: 'REFERÊNCIA DA API',
      it: 'RIFERIMENTO API',
      vi: 'THAM CHIẾU API',
    },
    items: [
      {
        id: 'models',
        title: {
          en: 'Models List',
          zh: '获取模型列表',
          ko: '모델 목록',
          ja: 'モデル一覧',
          ru: 'Список моделей',
          es: 'Lista de modelos',
          pt: 'Lista de modelos',
          it: 'Elenco modelli',
          vi: 'Danh sách mô hình',
        },
        icon: 'file-text',
      },
      {
        id: 'chat',
        title: {
          en: 'Chat Completions',
          zh: '聊天完成',
          ko: '채팅 완성',
          ja: 'チャット補完',
          ru: 'Chat Completions',
          es: 'Chat Completions',
          pt: 'Chat Completions',
          it: 'Chat Completions',
          vi: 'Chat Completions',
        },
        icon: 'message-square',
      },
      {
        id: 'embeddings',
        title: {
          en: 'Embeddings',
          zh: '文本嵌入',
          ko: '임베딩',
          ja: '埋め込み',
          ru: 'Эмбеддинги',
          es: 'Embeddings',
          pt: 'Embeddings',
          it: 'Embeddings',
          vi: 'Embeddings',
        },
        icon: 'file-code',
      },
      {
        id: 'images',
        title: {
          en: 'Image Generation',
          zh: '图像生成',
          ko: '이미지 생성',
          ja: '画像生成',
          ru: 'Генерация изображений',
          es: 'Generación de imágenes',
          pt: 'Geração de imagens',
          it: 'Generazione di immagini',
          vi: 'Tạo ảnh',
        },
        icon: 'image',
      },
      {
        id: 'gpt-image-2',
        title: {
          en: 'GPT Image 2',
          zh: 'GPT Image 2',
          ko: 'GPT Image 2',
          ja: 'GPT Image 2',
          ru: 'GPT Image 2',
          es: 'GPT Image 2',
          pt: 'GPT Image 2',
          it: 'GPT Image 2',
          vi: 'GPT Image 2',
        },
        icon: 'image',
      },
      {
        id: 'nano-banana-pro',
        title: {
          en: 'NanoBanana Pro',
          zh: 'NanoBanana Pro',
          ko: 'NanoBanana Pro',
          ja: 'NanoBanana Pro',
          ru: 'NanoBanana Pro',
          es: 'NanoBanana Pro',
          pt: 'NanoBanana Pro',
          it: 'NanoBanana Pro',
          vi: 'NanoBanana Pro',
        },
        icon: 'image',
      },
      {
        id: 'nano-banana-pro-edit',
        title: {
          en: 'NanoBananaPro Edit',
          zh: 'NanoBananaPro Edit',
          ko: 'NanoBananaPro Edit',
          ja: 'NanoBananaPro Edit',
          ru: 'NanoBananaPro Edit',
          es: 'NanoBananaPro Edit',
          pt: 'NanoBananaPro Edit',
          it: 'NanoBananaPro Edit',
          vi: 'NanoBananaPro Edit',
        },
        icon: 'image',
      },
    ],
  },
  {
    title: {
      en: 'GUIDES',
      zh: '指南',
      ko: '가이드',
      ja: 'ガイド',
      ru: 'РУКОВОДСТВА',
      es: 'GUÍAS',
      pt: 'GUIAS',
      it: 'GUIDE',
      vi: 'HƯỚNG DẪN',
    },
    items: [
      {
        id: 'claude-code',
        title: {
          en: 'Claude Code Setup',
          zh: 'Claude Code 设置',
          ko: 'Claude Code 설정',
          ja: 'Claude Code セットアップ',
          ru: 'Настройка Claude Code',
          es: 'Configuración de Claude Code',
          pt: 'Configuração do Claude Code',
          it: 'Configurazione di Claude Code',
          vi: 'Cài đặt Claude Code',
        },
        icon: 'terminal',
      },
      {
        id: 'claude-desktop',
        title: {
          en: 'Claude Desktop Setup',
          zh: 'Claude Desktop 设置',
          ko: 'Claude Desktop 설정',
          ja: 'Claude Desktop セットアップ',
          ru: 'Настройка Claude Desktop',
          es: 'Configuración de Claude Desktop',
          pt: 'Configuração do Claude Desktop',
          it: 'Configurazione di Claude Desktop',
          vi: 'Cài đặt Claude Desktop',
        },
        icon: 'terminal',
      },
      {
        id: 'codex',
        title: {
          en: 'OpenAI Codex Setup',
          zh: 'OpenAI Codex 设置',
          ko: 'OpenAI Codex 설정',
          ja: 'OpenAI Codex セットアップ',
          ru: 'Настройка OpenAI Codex',
          es: 'Configuración de OpenAI Codex',
          pt: 'Configuração do OpenAI Codex',
          it: 'Configurazione di OpenAI Codex',
          vi: 'Cài đặt OpenAI Codex',
        },
        icon: 'code',
      },
      {
        id: 'codex-desktop',
        title: {
          en: 'Codex Desktop Setup',
          zh: 'Codex 桌面端设置',
          ko: 'Codex Desktop 설정',
          ja: 'Codex Desktop セットアップ',
          ru: 'Настройка Codex Desktop',
          es: 'Configuración de Codex Desktop',
          pt: 'Configuração do Codex Desktop',
          it: 'Configurazione di Codex Desktop',
          vi: 'Cài đặt Codex Desktop',
        },
        icon: 'code',
      },
      {
        id: 'opencode',
        title: {
          en: 'OpenCode Setup',
          zh: 'OpenCode 设置',
          ko: 'OpenCode 설정',
          ja: 'OpenCode セットアップ',
          ru: 'Настройка OpenCode',
          es: 'Configuración de OpenCode',
          pt: 'Configuração do OpenCode',
          it: 'Configurazione di OpenCode',
          vi: 'Cài đặt OpenCode',
        },
        icon: 'terminal',
      },
      {
        id: 'openclaw',
        title: {
          en: 'OpenClaw Setup',
          zh: 'OpenClaw 设置',
          ko: 'OpenClaw 설정',
          ja: 'OpenClaw セットアップ',
          ru: 'Настройка OpenClaw',
          es: 'Configuración de OpenClaw',
          pt: 'Configuração do OpenClaw',
          it: 'Configurazione di OpenClaw',
          vi: 'Cài đặt OpenClaw',
        },
        icon: 'terminal',
      },
      {
        id: 'hermes',
        title: {
          en: 'Hermes Agent Setup',
          zh: 'Hermes Agent 设置',
          ko: 'Hermes Agent 설정',
          ja: 'Hermes Agent セットアップ',
          ru: 'Настройка Hermes Agent',
          es: 'Configuración de Hermes Agent',
          pt: 'Configuração do Hermes Agent',
          it: 'Configurazione di Hermes Agent',
          vi: 'Cài đặt Hermes Agent',
        },
        icon: 'terminal',
      },
      {
        id: 'deepseek-harness',
        title: {
          en: 'DeepSeek Harness Setup',
          zh: 'DeepSeek Harness 设置',
          ko: 'DeepSeek Harness 설정',
          ja: 'DeepSeek Harness セットアップ',
          ru: 'Настройка DeepSeek Harness',
          es: 'Configuración de DeepSeek Harness',
          pt: 'Configuração do DeepSeek Harness',
          it: 'Configurazione di DeepSeek Harness',
          vi: 'Cài đặt DeepSeek Harness',
        },
        icon: 'terminal',
      },
      {
        id: 'trae',
        title: {
          en: 'Trae Setup',
          zh: 'Trae 设置',
          ko: 'Trae 설정',
          ja: 'Trae セットアップ',
          ru: 'Настройка Trae',
          es: 'Configuración de Trae',
          pt: 'Configuração do Trae',
          it: 'Configurazione di Trae',
          vi: 'Cài đặt Trae',
        },
        icon: 'terminal',
      },
      {
        id: 'error-handling',
        title: {
          en: 'Error Handling',
          zh: '错误处理',
          ko: '오류 처리',
          ja: 'エラー処理',
          ru: 'Обработка ошибок',
          es: 'Manejo de errores',
          pt: 'Tratamento de erros',
          it: 'Gestione degli errori',
          vi: 'Xử lý lỗi',
        },
        icon: 'alert-triangle',
      },
      {
        id: 'examples',
        title: {
          en: 'Code Examples',
          zh: '代码示例',
          ko: '코드 예제',
          ja: 'コード例',
          ru: 'Примеры кода',
          es: 'Ejemplos de código',
          pt: 'Exemplos de código',
          it: 'Esempi di codice',
          vi: 'Ví dụ mã',
        },
        icon: 'code',
      },
    ],
  },
];
