import type { LocalizedString } from '../i18n';

export interface NavItem {
  id: string;
  title: LocalizedString;
  icon?: string;
}

export interface NavGroup {
  title: LocalizedString;
  items: NavItem[];
}

export const navigation: NavGroup[] = [
  {
    title: {
      en: 'OVERVIEW',
      zh: '概览',
      'zh-tw': '概覽',
      ko: '개요',
      ja: '概要',
      ru: 'ОБЗОР',
      es: 'RESUMEN',
      pt: 'VISÃO GERAL',
      it: 'PANORAMICA',
      fr: 'APERÇU',
      de: 'ÜBERSICHT',
      vi: 'TỔNG QUAN',
    },
    items: [
      {
        id: 'getting-started',
        title: {
          en: 'Getting Started',
          zh: '快速开始',
          'zh-tw': '快速開始',
          ko: '시작하기',
          ja: 'はじめに',
          ru: 'Начало работы',
          es: 'Primeros pasos',
          pt: 'Primeiros passos',
          it: 'Per iniziare',
          fr: 'Premiers pas',
          de: 'Erste Schritte',
          vi: 'Bắt đầu',
        },
        icon: 'rocket',
      },
      {
        id: 'faq',
        title: {
          en: 'FAQ',
          zh: '常见问题',
          'zh-tw': '常見問題',
          ko: 'FAQ',
          ja: 'よくある質問',
          ru: 'FAQ',
          es: 'Preguntas frecuentes',
          pt: 'Perguntas frequentes',
          it: 'Domande frequenti',
          fr: 'FAQ',
          de: 'FAQ',
          vi: 'Câu hỏi thường gặp',
        },
        icon: 'help-circle',
      },
    ],
  },
  {
    title: {
      en: 'AUTHENTICATION',
      zh: '认证',
      'zh-tw': '認證',
      ko: '인증',
      ja: '認証',
      ru: 'АУТЕНТИФИКАЦИЯ',
      es: 'AUTENTICACIÓN',
      pt: 'AUTENTICAÇÃO',
      it: 'AUTENTICAZIONE',
      fr: 'AUTHENTIFICATION',
      de: 'AUTHENTIFIZIERUNG',
      vi: 'XÁC THỰC',
    },
    items: [
      {
        id: 'authentication',
        title: {
          en: 'Authentication',
          zh: '身份认证',
          'zh-tw': '身分認證',
          ko: '인증',
          ja: '認証',
          ru: 'Аутентификация',
          es: 'Autenticación',
          pt: 'Autenticação',
          it: 'Autenticazione',
          fr: 'Authentification',
          de: 'Authentifizierung',
          vi: 'Xác thực',
        },
        icon: 'key',
      },
    ],
  },
  {
    title: {
      en: 'API REFERENCE',
      zh: 'API 参考',
      'zh-tw': 'API 參考',
      ko: 'API 레퍼런스',
      ja: 'API リファレンス',
      ru: 'СПРАВОЧНИК API',
      es: 'REFERENCIA DE API',
      pt: 'REFERÊNCIA DA API',
      it: 'RIFERIMENTO API',
      fr: 'RÉFÉRENCE API',
      de: 'API-REFERENZ',
      vi: 'THAM CHIẾU API',
    },
    items: [
      {
        id: 'models',
        title: {
          en: 'Models List',
          zh: '获取模型列表',
          'zh-tw': '取得模型列表',
          ko: '모델 목록',
          ja: 'モデル一覧',
          ru: 'Список моделей',
          es: 'Lista de modelos',
          pt: 'Lista de modelos',
          it: 'Elenco modelli',
          fr: 'Liste des modèles',
          de: 'Modellliste',
          vi: 'Danh sách mô hình',
        },
        icon: 'file-text',
      },
      {
        id: 'chat',
        title: {
          en: 'Chat Completions',
          zh: '聊天完成',
          'zh-tw': '聊天完成',
          ko: '채팅 완성',
          ja: 'チャット補完',
          ru: 'Chat Completions',
          es: 'Chat Completions',
          pt: 'Chat Completions',
          it: 'Chat Completions',
          fr: 'Chat Completions',
          de: 'Chat Completions',
          vi: 'Chat Completions',
        },
        icon: 'message-square',
      },
      {
        id: 'embeddings',
        title: {
          en: 'Embeddings',
          zh: '文本嵌入',
          'zh-tw': '文字嵌入',
          ko: '임베딩',
          ja: '埋め込み',
          ru: 'Эмбеддинги',
          es: 'Embeddings',
          pt: 'Embeddings',
          it: 'Embeddings',
          fr: 'Embeddings',
          de: 'Embeddings',
          vi: 'Embeddings',
        },
        icon: 'file-code',
      },
      {
        id: 'images',
        title: {
          en: 'Image Generation',
          zh: '图像生成',
          'zh-tw': '影像生成',
          ko: '이미지 생성',
          ja: '画像生成',
          ru: 'Генерация изображений',
          es: 'Generación de imágenes',
          pt: 'Geração de imagens',
          it: 'Generazione di immagini',
          fr: "Génération d'images",
          de: 'Bildgenerierung',
          vi: 'Tạo ảnh',
        },
        icon: 'image',
      },
      {
        id: 'gpt-image-2',
        title: {
          en: 'GPT Image 2',
          zh: 'GPT Image 2',
          'zh-tw': 'GPT Image 2',
          ko: 'GPT Image 2',
          ja: 'GPT Image 2',
          ru: 'GPT Image 2',
          es: 'GPT Image 2',
          pt: 'GPT Image 2',
          it: 'GPT Image 2',
          fr: 'GPT Image 2',
          de: 'GPT Image 2',
          vi: 'GPT Image 2',
        },
        icon: 'image',
      },
      {
        id: 'nano-banana-pro',
        title: {
          en: 'NanoBanana Pro',
          zh: 'NanoBanana Pro',
          'zh-tw': 'NanoBanana Pro',
          ko: 'NanoBanana Pro',
          ja: 'NanoBanana Pro',
          ru: 'NanoBanana Pro',
          es: 'NanoBanana Pro',
          pt: 'NanoBanana Pro',
          it: 'NanoBanana Pro',
          fr: 'NanoBanana Pro',
          de: 'NanoBanana Pro',
          vi: 'NanoBanana Pro',
        },
        icon: 'image',
      },
      {
        id: 'nano-banana-pro-edit',
        title: {
          en: 'NanoBananaPro Edit',
          zh: 'NanoBananaPro Edit',
          'zh-tw': 'NanoBananaPro Edit',
          ko: 'NanoBananaPro Edit',
          ja: 'NanoBananaPro Edit',
          ru: 'NanoBananaPro Edit',
          es: 'NanoBananaPro Edit',
          pt: 'NanoBananaPro Edit',
          it: 'NanoBananaPro Edit',
          fr: 'NanoBananaPro Edit',
          de: 'NanoBananaPro Edit',
          vi: 'NanoBananaPro Edit',
        },
        icon: 'image',
      },
    ],
  },
  {
    title: {
      en: 'GUIDES',
      zh: '指南',
      'zh-tw': '指南',
      ko: '가이드',
      ja: 'ガイド',
      ru: 'РУКОВОДСТВА',
      es: 'GUÍAS',
      pt: 'GUIAS',
      it: 'GUIDE',
      fr: 'GUIDES',
      de: 'ANLEITUNGEN',
      vi: 'HƯỚNG DẪN',
    },
    items: [
      {
        id: 'claude-code',
        title: {
          en: 'Claude Code Setup',
          zh: 'Claude Code 设置',
          'zh-tw': 'Claude Code 設定',
          ko: 'Claude Code 설정',
          ja: 'Claude Code セットアップ',
          ru: 'Настройка Claude Code',
          es: 'Configuración de Claude Code',
          pt: 'Configuração do Claude Code',
          it: 'Configurazione di Claude Code',
          fr: 'Configuration de Claude Code',
          de: 'Claude Code einrichten',
          vi: 'Cài đặt Claude Code',
        },
        icon: 'terminal',
      },
      {
        id: 'claude-desktop',
        title: {
          en: 'Claude Desktop Setup',
          zh: 'Claude Desktop 设置',
          'zh-tw': 'Claude Desktop 設定',
          ko: 'Claude Desktop 설정',
          ja: 'Claude Desktop セットアップ',
          ru: 'Настройка Claude Desktop',
          es: 'Configuración de Claude Desktop',
          pt: 'Configuração do Claude Desktop',
          it: 'Configurazione di Claude Desktop',
          fr: 'Configuration de Claude Desktop',
          de: 'Claude Desktop einrichten',
          vi: 'Cài đặt Claude Desktop',
        },
        icon: 'terminal',
      },
      {
        id: 'codex',
        title: {
          en: 'Codex CLI Setup',
          zh: 'Codex CLI 设置',
          'zh-tw': 'Codex CLI 設定',
          ko: 'Codex CLI 설정',
          ja: 'Codex CLI セットアップ',
          ru: 'Настройка Codex CLI',
          es: 'Configuración de Codex CLI',
          pt: 'Configuração do Codex CLI',
          it: 'Configurazione di Codex CLI',
          fr: 'Configuration de Codex CLI',
          de: 'Codex CLI einrichten',
          vi: 'Cài đặt Codex CLI',
        },
        icon: 'code',
      },
      {
        id: 'codex-desktop',
        title: {
          en: 'Codex Desktop Setup',
          zh: 'Codex Desktop 设置',
          'zh-tw': 'Codex Desktop 設定',
          ko: 'Codex Desktop 설정',
          ja: 'Codex Desktop セットアップ',
          ru: 'Настройка Codex Desktop',
          es: 'Configuración de Codex Desktop',
          pt: 'Configuração do Codex Desktop',
          it: 'Configurazione di Codex Desktop',
          fr: 'Configuration de Codex Desktop',
          de: 'Codex Desktop einrichten',
          vi: 'Cài đặt Codex Desktop',
        },
        icon: 'code',
      },
      {
        id: 'opencode',
        title: {
          en: 'OpenCode Setup',
          zh: 'OpenCode 设置',
          'zh-tw': 'OpenCode 設定',
          ko: 'OpenCode 설정',
          ja: 'OpenCode セットアップ',
          ru: 'Настройка OpenCode',
          es: 'Configuración de OpenCode',
          pt: 'Configuração do OpenCode',
          it: 'Configurazione di OpenCode',
          fr: 'Configuration d’OpenCode',
          de: 'OpenCode einrichten',
          vi: 'Cài đặt OpenCode',
        },
        icon: 'terminal',
      },
      {
        id: 'openclaw',
        title: {
          en: 'OpenClaw Setup',
          zh: 'OpenClaw 设置',
          'zh-tw': 'OpenClaw 設定',
          ko: 'OpenClaw 설정',
          ja: 'OpenClaw セットアップ',
          ru: 'Настройка OpenClaw',
          es: 'Configuración de OpenClaw',
          pt: 'Configuração do OpenClaw',
          it: 'Configurazione di OpenClaw',
          fr: 'Configuration d’OpenClaw',
          de: 'OpenClaw einrichten',
          vi: 'Cài đặt OpenClaw',
        },
        icon: 'terminal',
      },
      {
        id: 'hermes',
        title: {
          en: 'Hermes Agent Setup',
          zh: 'Hermes Agent 设置',
          'zh-tw': 'Hermes Agent 設定',
          ko: 'Hermes Agent 설정',
          ja: 'Hermes Agent セットアップ',
          ru: 'Настройка Hermes Agent',
          es: 'Configuración de Hermes Agent',
          pt: 'Configuração do Hermes Agent',
          it: 'Configurazione di Hermes Agent',
          fr: 'Configuration de Hermes Agent',
          de: 'Hermes Agent einrichten',
          vi: 'Cài đặt Hermes Agent',
        },
        icon: 'terminal',
      },
      {
        id: 'deepseek-harness',
        title: {
          en: 'DeepSeek Harness Setup',
          zh: 'DeepSeek Harness 设置',
          'zh-tw': 'DeepSeek Harness 設定',
          ko: 'DeepSeek Harness 설정',
          ja: 'DeepSeek Harness セットアップ',
          ru: 'Настройка DeepSeek Harness',
          es: 'Configuración de DeepSeek Harness',
          pt: 'Configuração do DeepSeek Harness',
          it: 'Configurazione di DeepSeek Harness',
          fr: 'Configuration de DeepSeek Harness',
          de: 'DeepSeek Harness einrichten',
          vi: 'Cài đặt DeepSeek Harness',
        },
        icon: 'terminal',
      },
      {
        id: 'trae',
        title: {
          en: 'Trae Setup',
          zh: 'Trae 设置',
          'zh-tw': 'Trae 設定',
          ko: 'Trae 설정',
          ja: 'Trae セットアップ',
          ru: 'Настройка Trae',
          es: 'Configuración de Trae',
          pt: 'Configuração do Trae',
          it: 'Configurazione di Trae',
          fr: 'Configuration de Trae',
          de: 'Trae einrichten',
          vi: 'Cài đặt Trae',
        },
        icon: 'terminal',
      },
      {
        id: 'error-handling',
        title: {
          en: 'Error Handling',
          zh: '错误处理',
          'zh-tw': '錯誤處理',
          ko: '오류 처리',
          ja: 'エラー処理',
          ru: 'Обработка ошибок',
          es: 'Manejo de errores',
          pt: 'Tratamento de erros',
          it: 'Gestione degli errori',
          fr: 'Gestion des erreurs',
          de: 'Fehlerbehandlung',
          vi: 'Xử lý lỗi',
        },
        icon: 'alert-triangle',
      },
      {
        id: 'examples',
        title: {
          en: 'Code Examples',
          zh: '代码示例',
          'zh-tw': '程式碼範例',
          ko: '코드 예제',
          ja: 'コード例',
          ru: 'Примеры кода',
          es: 'Ejemplos de código',
          pt: 'Exemplos de código',
          it: 'Esempi di codice',
          fr: 'Exemples de code',
          de: 'Codebeispiele',
          vi: 'Ví dụ mã',
        },
        icon: 'code',
      },
    ],
  },
];
